language: java

sudo: false

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

jdk:
  - openjdk7
  - oraclejdk8

os:
  - linux

notifications:
  email: false
  
branches:
  only:
    - master

notifications:
  email: false
